-- Could not auto-generate a down migration
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE public.columns ALTER COLUMN position SET DEFAULT '1000.0';
-- ALTER TABLE public.columns ALTER COLUMN created_at SET DEFAULT now();
