-- Could not auto-generate a down migration
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE public.columns ADD CONSTRAINT columns_position_unique UNIQUE (position);
-- ALTER TABLE public.columns ADD CONSTRAINT columns_created_at_unique UNIQUE (created_at);
